### ISSUE TITLE
lolcat no longer working, i have ruby installed.

### ISSUE THREAD

**Issue by A-Random-Lantern** [busyloop/lolcat#112]
```
a_random_lantern@hal-9000:~$ lolcat
bash: /usr/local/bin/lolcat: /usr/bin/ruby2.5: bad interpreter: No such file or directory
```
I don't know why this is happening all of a sudden, it used to work before.

**Comment by danthe1st** [comment]
I have the same problem after updating my system. Ruby is on version 2.7 now.

**Comment by m-o-e** [comment]
What OS?  Have you tried snap install?

**Comment by danthe1st** [comment]
Yes, it didn't change anything. I have also reinstalled ruby.

**Comment by m-o-e** [comment]
What OS is this on and how was lolcat installed?

**Comment by danthe1st** [comment]
I use ubuntu on WSL:
```
neofetch
            .-/+oossssoo+/-.               dan@Daniellaptop
        `:+ssssssssssssssssss+:`           ----------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04 LTS on Windows 10 x86_64
    .ossssssssssssssssssdMMMNysssso.       Kernel: 4.19.104-microsoft-standard
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 6 hours, 37 mins
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2246 (dpkg), 4 (snap)
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.0.16
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   CPU: Intel i7-7500U (4) @ 2.903GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 330MiB / 6280MiB
ossyNMMMNyMMhsssssssssssssshmmmhssssssso
ossyNMMMNyMMhsssssssssssssshmmmhssssssso
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by danthe1st** [comment]
```
 ✘ dan@Daniellaptop  ~  sudo snap remove ruby
ruby removed 
dan@Daniellaptop  ~  sudo snap install lolcat
snap "lolcat" is already installed, see 'snap help refresh'
dan@Daniellaptop  ~  sudo snap remove lolcat
lolcat removed
dan@Daniellaptop  ~  sudo snap install lolcat
lolcat 100.0.1 from moe (busyloop) installed
dan@Daniellaptop  ~  echo test | lolcat
Traceback (most recent call last):
2: from /usr/local/bin/lolcat:23:in `<main>'
1: from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat
(Gem::GemNotFoundException)
✘ dan@Daniellaptop  ~  whereis ruby
ruby: /usr/bin/ruby /usr/bin/ruby2.7 /usr/lib/x86_64-linux-gnu/ruby /usr/lib/ruby /usr/share/man/man1/ruby.1.gz
```

**Comment by m-o-e** [comment]
What does `which lolcat` say? 🤔

**Comment by danthe1st** [comment]
```
$ which lolcat
/usr/local/bin/lolcat
$ head "$(which lolcat)"
#!/usr/bin/ruby2.7
#
# This file was generated by RubyGems.
#
# The application 'lolcat' is installed as part of a gem, and
# this file is here to facilitate running it.
#                                                                                                                                                                                                                                               require 'rubygems'
```

**Comment by danthe1st** [comment]
I found a workaround:
```
sudo mv /usr/local/bin/lolcat lolcat
$ sudo snap remove lolcat.bkp
lolcat removed
$ sudo snap install lolcat
```

**Comment by m-o-e** [comment]
Yes, it looks like you had a lolcat installed from a different source
(ever done a `gem install lolcat` or `apt install lolcat` in the past?).

Lolcat installed from snap should be located in `/snap/bin/lolcat`. 🙂

**Comment by danthe1st** [comment]
Yes, I used `apt` previously and I updated using `apt` (`sudo do-release-upgrade`). However, `lolcat` was not available there after the update.

**Comment by m-o-e** [comment]
Hmm yep. Will need to look into ways to make this all less confusing.
Glad you figured it out tho 👍

**Comment by danthe1st** [comment]
Let's see if it works for the original poster, too.

**Comment by A-Random-Lantern** [comment]
Yeah it worked for me, thanks.

Late reply I know

**Comment by LinuxOnTheDesktop** [comment]
I encountered the same problem on Linux Mint 21. I had lolcat installed, via `apt` I think, on Mint 20.3, and all worked. But now:

```
$ lolcat
bash: /usr/local/bin/lolcat: /usr/bin/ruby2.7: bad interpreter: No such file or directory
$ which ruby
/usr/bin/ruby
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
$ apt list ruby
Listing... Done
ruby/jammy,now 1:3.0~exp1 amd64 [installed]
ruby/jammy 1:3.0~exp1 i386
```

EDIT: on the proposed workaround: Linux Mint does not have snaps enabled by default, and I do not fancy enabling them.

**Comment by m-o-e** [comment]
I don't know the ruby setup in mint but you can most likely fix it
with `gem install lolcat` (or `sudo gem install lolcat`).

You may need to remove any previously installed version first
(either with the package manager you used, or with `sudo rm -f /usr/local/bin/lolcat`)

**Comment by LinuxOnTheDesktop** [comment]
@m-o-e 

Marvellous: that worked. Thank you. I did indeed have to use `sudo`.

**Comment by LinuxOnTheDesktop** [comment]
Ah: sorry to bang on, but suddently I see the following!

```
neofetch | lolcat
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1401:in `rescue in block in activate_dependencies': Could not find 'paint' (~> 2.1) among 94 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/<redacted>/.gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0' at: /var/lib/gems/3.0.0/specifications/lolcat-100.0.1.gemspec, execute `gem env` for more information
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1398:in `block in activate_dependencies'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `synchronize'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `activate_bin_path'
	from /usr/local/bin/lolcat:25:in `<main>'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:311:in `to_specs': Could not find 'paint' (~> 2.1) among 94 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/<redacted>/.gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0' , execute `gem env` for more information
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `block in activate_dependencies'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `synchronize'
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `activate_bin_path'
	from /usr/local/bin/lolcat:25:in `<main>'
```

**Comment by LinuxOnTheDesktop** [comment]
. . And, after reinstalling lolcat, again, the problem disappeared once more. I reinstalled lolcat _via apt_. So that was the needful in my case.

**Comment by ernstki** [comment]
> I don't know why this is happening all of a sudden, it used to work before.

For those who find themselves here after doing a web search for this error message, I suggest having a look at the values of `GEM_PATH` and `GEM_HOME`. Try `unset`ting both of them and see if you get a different result.

ref.: https://bbs.archlinux.org/viewtopic.php?pid=1831370#p1831370
