### ISSUE TITLE
Error when attempting to cat /dev/urandom | lolcat

### ISSUE THREAD

**Issue by radrow** [busyloop/lolcat#65]
Command `cat /dev/urandom | lolcat` constantly gives me following error:

```
Traceback (most recent call last):
        10: from /usr/bin/lolcat:23:in `<main>'
         9: from /usr/bin/lolcat:23:in `load'
         8: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/bin/lolcat:32:in `<top (required)>'
         7: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/cat.rb:102:in cat!'
         6: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/cat.rb:102:in `each'
         5: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/cat.rb:108:in `block in cat!'
         4: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/lol.rb:42:in `cat'
         3: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/lol.rb:42:in `each'
         2: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/lol.rb:44:in `block in cat'
         1: from /usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/lol.rb:53:in `println'
/usr/lib/ruby/gems/2.5.0/gems/lolcat-90.8.8/lib/lolcat/lol.rb:53:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
```

It completely blocks my work with the program, what are chances to fix the problem?

**Comment by m-o-e** [comment]
Sorry, this is not a problem in lolcat.

You don't want to print `/dev/urandom` to your terminal.
Try what happens when you do `cat /dev/urandom`.

lolcat protects you from shredding your terminal.

If you really need to inspect the universe then `hexdump /dev/urandom | lolcat`
is the command you want to use.
