### ISSUE TITLE
ruby-paint v2.1.0 doesn't satisfy dependency

### ISSUE THREAD

**Issue by murtezayesil** [busyloop/lolcat#88]
Lolcat prints following error even when `lolcat --help` is run
```
Traceback (most recent call last):
	8: from /usr/bin/lolcat:23:in `<main>'
	7: from /usr/lib64/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	6: from /usr/lib64/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	5: from /usr/lib64/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	4: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	3: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	2: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	1: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/usr/lib64/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'paint' (~> 2.0.0) - did find: [paint-2.1.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/murteza/.gem/ruby/2.6.0:/usr/lib64/ruby/gems/2.6.0', execute `gem env` for more information
```
More info
OS : Solus 64bit
Terminal: gnome-terminal
```
> eopkg info lolcat
Installed package:
Name                : lolcat, version: 99.9.21, release: 3
Summary             : Rainbows and unicorns!
Description         : Lolcat is an utility which concatenates like similar to cat command and adds rainbow coloring to it. Lolcat is primarily used
                      for rainbow coloring of text in Linux Terminal.
Licenses            : BSD-3-Clause
Component           : programming.ruby
Dependencies        : ruby-manpages ruby-paint ruby-trollop 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 64.00 KB
Reverse Dependencies: 
```
```
> eopkg info ruby-paint
Installed package:
Name                : ruby-paint, version: 2.1.0, release: 3
Summary             : Ruby gem for ANSI terminal colors
Description         : Paint creates terminal colors and effects for you. It
                      combines the strengths of term-ansicolor, rainbow, and
                      similar projects into a simple to use, however still
                      flexible terminal colors gem with no core extensions by
                      default.
Licenses            : MIT
Component           : programming.ruby
Dependencies        : ruby 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 33.00 KB
Reverse Dependencies: lolcat 
```
```
> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.1
  - RUBY VERSION: 2.6.0 (2018-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /home/murteza/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/murteza/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib64/ruby/gems/2.6.0
     - /home/murteza/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/murteza/.sdkman/candidates/java/current/bin
     - /home/murteza/.sdkman/candidates/gradle/current/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/local/bin
     - /snap/bin
     - /home/murteza/.local/bin
```

**Comment by m-o-e** [comment]
It looks like lolcat hasn't been properly packaged in Solus (it doesn't install all required dependencies). This bug should go to the package maintainer.

In the meantime you can try installing it the ruby way by first removing the Solus package and then doing `sudo gem install lolcat`.

**Comment by murtezayesil** [comment]
`sudo gem install lolcat` worked very well 👍 Thanks
![2019-03-29-225128_1366x768_scrot](https://user-images.githubusercontent.com/24689015/55249147-9e2e5a80-5275-11e9-8065-010cf6bf4ebb.png)
